#!/bin/bash

# Creates a basic website file structure with a stylesheet, javascript file, and image folder.
# Install in ~/bin and follow with the command 'chmod +x ~/bin/webmake'.
# Usage: webmake <name of project>

if [ $# -eq 0 ]; then
  echo "Please provide a name for the project."
  exit 1
fi

if ! command -v git &> /dev/null
then
    echo "Git is not installed. Please install Git and try again."
    exit 1
fi

pid=$1
mkdir $pid && cd $pid
touch index.html
cat > index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="assets/css/main.css">
  <script src="assets/js/script.js"></script>
</head>
<body>
  
</body>
</html>
EOF
mkdir -p assets/{images,css,js}
touch assets/css/main.css 
touch assets/js/script.js
git init
